export {default as CrewInfo} from './Crew/CrewInfo'
export {default as CrewMemebers} from './Crew/CrewMemebers'
export {default as Planet} from './Destination/Planet'
export {default as PlanetInfo} from './Destination/PlanetInfo'
export {default as HomeButton} from './Home/HomeButton'
export {default as HomeText} from './Home/HomeText'
export {default as NavBar} from './Nav/NavBar'
export {default as NavItems} from './Nav/NavItems'
export {default as About} from './Technology/About'
export {default as Term} from './Technology/Term'
export{default as Music} from './Music'